version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile      
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://{user}:{pw}@db:5432/{db}
      SECRET_KEY: ${SECRET_KEY}
    env_file: ../.env


volumes:
  db-data:
